name: Build and Deploy
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Build
        run: |
          rm -rf dist
          npm install
          npm run build
          cp -r src/assets/* dist/
      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_GLADECK_2000 }}"
          projectId: "${{ vars.PROJECT_ID }}"
          channelId: live
